### ISSUE TITLE
NR cell detection on MTK 800U

### ISSUE THREAD

**Issue by ElCresh** [mroczis/netmonster-core#13]
I've used netmonster-core on Realme 7 5G and on Xiaomi Redmi Note 9t 5G with Mediatek 800U. I've found a particular behaviour with NR cell. First time is detected without ARFCN and PCI. Second time is detected only NR carrier with only ARFCN and PCI. This appears on DSS and NR in LTE_NR configuration.

![image](https://user-images.githubusercontent.com/9625583/114851358-0b23d700-9de2-11eb-8def-fababb894dbb.png)
![image](https://user-images.githubusercontent.com/9625583/114851374-0e1ec780-9de2-11eb-8070-bc0dbf6447e9.png)

[report (3).txt](https://github.com/mroczis/netmonster-core/files/6316963/report.3.txt)

**Comment by mroczis** [comment]
NetMonster Core does not provide any data-caching and retrieves everything when requested. Due to constant updates from RIL and lower layers data change all the time. There might be some calls returning "not complete" data sets as you mention. If you require datasets that contain full cell identities, you can built caching-layer on top the library and filter out results you consider invalid.

**Comment by ElCresh** [comment]
Yes, I've build a cache-layer but I was wondering if some filter was not working properly. That was my concern. Because when NR data arrives LTE and neighborhood cell disapear.
