### ISSUE TITLE
LTE-A 3CA BW has incorrect value

### ISSUE THREAD

**Issue by macfeaster** [mroczis/netmonster-core#4]
Hi,

Thanks for a great app! Dug through some of your source and wow, I had no idea it was such a pain to get the information displayed in the app.

I had a friend download the app and try it on a Xiaomi Mi 10 and got some interesting results. NetMonster correctly identifies LTE-A 3CA carrier agg with B1+B7+B20, but the bandwidth identified is not correct. Looking at 4636 it's evident that the phone is using 3CA 10+10+10MHz on B1+7+20, but NetMonster only shows 10 MHz. Speed tests are also reaching speeds which should be technically impossible on only 10 MHz.

I'm attaching some screenshots, as well as OCR'd LTE physical cell config since I saw in the source that you use that as an information source.

![99127063_568433953814479_259767125369946112_n](https://user-images.githubusercontent.com/6403471/82371227-1e83c200-9a1a-11ea-9573-9e214a08f67c.jpg)
![98276385_700696930730791_1095795372963397632_n (1)](https://user-images.githubusercontent.com/6403471/82371235-217eb280-9a1a-11ea-8609-224770a11dcd.jpg)

```
{
	{
		mConnectionStatus=PrimaryServing,
		mCellBandwidthDownlinkKhz=10000,
		mRat=19,
		mFrequencyRange=2,
		mChannelNumber=2147483647,
		mContextlds=[I@bd5822d,
		mPhysicalCellld=118
	},
	{
		mConnectionStatus=SecondaryServing,
		mCellBandwidthDownlinkKhz=10000,
		mRat=19,
		mFrequencyRange=2,
		mChannelNumber=2147483647,
		mContextlds=[I@3605362,
		mPhysicalCellld=94
	},
	{
		mConnectionStatus=SecondaryServing,
		mCellBandwidthDownlinkKhz=10000,
		mRat=19,
		mFrequencyRange=2,
		mChannelNumber=2147483647,
		mContextlds=[I@9378cf3,
		mPhysicalCellld=94
	}
}
```

**Comment by creg49** [comment]
I'm sorry my account is hacked I have no idea what your talking about want
to help me stop hacker I can't do anything to stop him,her thank u creg

On May 19, 2020 15:48, "Mauritz Zachrisson" <notifications@github.com>
wrote:

Hi,

Thanks for a great app! Dug through some of your source and wow, I had no
idea it was such a pain to get the information displayed in the app.

I had a friend download the app and try it on a Xiaomi Mi 10 and got some
interesting results. NetMonster correctly identifies LTE-A 3CA carrier agg
with B1+B7+B20, but the bandwidth identified is not correct. Looking at
4636 it's evident that the phone is using 3CA 10+10+10MHz on B1+7+20, but
NetMonster only shows 10 MHz. Speed tests are also reaching speeds which
should be technically impossible on only 10 MHz.

I'm attaching some screenshots, as well as OCR'd LTE physical cell config
since I saw in the source that you use that as an information source.

[image: 99127063_568433953814479_259767125369946112_n]
<https://user-images.githubusercontent.com/6403471/82371227-1e83c200-9a1a-11ea-9573-9e214a08f67c.jpg>
[image: 98276385_700696930730791_1095795372963397632_n (1)]
<https://user-images.githubusercontent.com/6403471/82371235-217eb280-9a1a-11ea-8609-224770a11dcd.jpg>

{
	{
		mConnectionStatus=PrimaryServing,
		mCellBandwidthDownlinkKhz=10000,
		mRat=19,
		mFrequencyRange=2,
		mChannelNumber=2147483647,
		mContextlds=[I@bd5822d,
		mPhysicalCellld=118
	},
	{
		mConnectionStatus=SecondaryServing,
		mCellBandwidthDownlinkKhz=10000,
		mRat=19,
		mFrequencyRange=2,
		mChannelNumber=2147483647,
		mContextlds=[I@3605362,
		mPhysicalCellld=94
	},
	{
		mConnectionStatus=SecondaryServing,
		mCellBandwidthDownlinkKhz=10000,
		mRat=19,
		mFrequencyRange=2,
		mChannelNumber=2147483647,
		mContextlds=[I@9378cf3,
		mPhysicalCellld=94
	}
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mroczis/netmonster-core/issues/4>, or unsubscribe
