### ISSUE TITLE
CA combinations wrong

### ISSUE THREAD

**Issue by Tweakandroid** [mroczis/netmonster-core#5]
The CA combinations doesn't show the right number. For example I have a tower that projects 900+1800+2100+2600mhz but since the new update It only shows 1800mhz all the time. Or showing only 3CA when Im connected to 4CA.
So the projecting of the LTE frequency in the app are not right.

**Comment by mroczis** [comment]
NetMonster Core fully depends on Android SDK and does directly interact with RIL. As you mention device software updates might break some functionalities.

If you think that issue is on library's side please send bug report from NetMonster application. In order to do that, go to app's settings, tap 5 times on 'Version' and then hit 'SEND' button on top-right corner. Make sure that your device is connected to at least two carriers when generating the report.

**Comment by QueenTallicia69-cloud** [comment]
Ok I'm Noob at this 
😁😁😁

**Comment by QueenTallicia69-cloud** [comment]
Sorry Just kidding I'm too wasted to Concentrate... Or not wasted enough. Euh never mind I'm GOING TO finish My Dilirium bear
