### ISSUE TITLE
Workaround to detect 5G NSA without READ_PHONE_STATE permission?

### ISSUE THREAD

**Issue by renaudk** [mroczis/netmonster-core#6]
Hello,

Since Android N, READ_PHONE_STATE permission is now considered as dangerous. 
Since Android R, it's now required to access SERVICE_STATE intent. 
It must be asked at runtime and the system ask for access to all the "Phone" permission group which can afraid users.

Do you know a workaround to detect 5G NSA without relying on SERVICE_STATE intent? 

BR,

**Comment by mroczis** [comment]
You are correct. Since Android R there's an official interface for NR NSA and LTE-A detection. Take a look at [TelephonyDisplayInfo](https://developer.android.com/reference/kotlin/android/telephony/TelephonyDisplayInfo) which can be obtained via [PhoneStateListener](https://developer.android.com/reference/kotlin/android/telephony/PhoneStateListener#onDisplayInfoChanged(android.telephony.TelephonyDisplayInfo)). However, this method also requires `READ_PHONE_STATE` permission. 

I fully agree that Android's handling of such permission is really unfortunate and loads of users have issues permitting access to so called "Phone" but as far as I know there's no other way.

**Comment by renaudk** [comment]
Maybe we can detect CellInfoNr with getAllCellInfo ? 
However, I don't know if this can work and if it is realiable on all 5G devices... maybe you have a feedback about this?

**Comment by mroczis** [comment]
This might be possible in future but not right now. Vast majority of 5G networks are NSA which means that LTE is still control plane hence you'll receive `CellInfoLte` from `getAllCellInfo()`.

Some phones do return `CellInfoNr` marking those entries as not-serving cells but you cannot rely on that. On other phones `SingalStrength` class will contain entry for NR. But some phones do not clear it once they disconnect from 5G. If you are willing to use it take a look at [NetMonster Core sample](https://github.com/mroczis/netmonster-core/blob/master/library/src/main/java/cz/mroczis/netmonster/core/telephony/mapper/cell/SignalStrengthMapper.kt). This works since Android 9 / API 29.
