### ISSUE TITLE
NETMONSTER - New maintener? 

### ISSUE THREAD

**Issue by Beat-YT** [mroczis/netmonster-core#70]
@mroczis 

I think that it's maybe time to find a new maintener for netmonster!

Thanks for your time

**Comment by eladts** [comment]
@Beat-YT Why do you think that? Remember NetMonster is a free app with no ads, so @mroczis gets no revenue from the work he does on the app and the library. Nevertheless the development seem to be active and issues are addressed.

**Comment by Beat-YT** [comment]
Oh I didn't saw that he fixed the issues!

I thought he was not active lol

**Comment by L31FY** [comment]
The app was just changed to have ads and an expensive subscription is required for location features now when it was previously functional in older versions and then removed for some reason, therefore paywalling a feature we had. I think it's time to uninstall unless someone else takes over or this is immediately reversed because it's the path of destruction.

**Comment by ExperiencersInternational** [comment]
> The app was just changed to have ads and an expensive subscription is required for location features now when it was previously functional in older versions and then removed for some reason, therefore paywalling a feature we had. I think it's time to uninstall unless someone else takes over or this is immediately reversed because it's the path of destruction. This is predatory and dishonest at best.

The ads are easily avoidable with an ad blocker and I have no issues with the location features apart from the fact that the eNB tool isn't that great and it doesn't provide me a hint based on eNB where a site might be anymore.

App is perfect, just a few minor issues for me.
