### ISSUE TITLE
What does this means

### ISSUE THREAD

**Issue by Beat-YT** [mroczis/netmonster-core#73]
![Screenshot_20230323-130349.jpg](https://user-images.githubusercontent.com/66485277/227280439-250627c0-23be-4121-bcf8-4e10635cafa7.jpg)

**Comment by ExperiencersInternational** [comment]
Not sure if you're still looking but in that space, it'll either show other technologies that you've located there (2G, 3G etc) or if you're roaming, the name of the network.

e.g. using O2 on an O2 SIM, with 2G and 3G located on the site (I should probably file a bug report for locating 2G/3G since it's extremely unreliable atm)

![Screenshot_20240731-134028](https://github.com/user-attachments/assets/e74274ab-47c5-4aea-b627-383d35f8b89b)

and O2 on an eSIM roaming from Plus PL (on the same sector on the same site)

![Screenshot_20240731-134247](https://github.com/user-attachments/assets/7448fd5f-b1f6-4dce-877d-c3456cbe69dd)
