### ISSUE TITLE
Automatic locations of LTE cell sites stopped working after Pixel 7 June 2023 update

### ISSUE THREAD

**Issue by eladts** [mroczis/netmonster-core#83]
Version 2.22.2 of NetMonster used to figure out by itself the location of many LTE sites, probably using some sort of triangulation. This is a very nice feature, but it stopped working on my Pixel 7 after the June 2023 update (QPR3). After I cleared the app data no LTE cell sites was automatically located.

**Comment by verimash** [comment]
Same problem (Poco M3 Pro phone and Poco M4). According to my research, the problem lies in the 404 error on the lbs-slb.mobile domain.yandex.net (a service by which you can find out the location without GPS). Base stations can be accessed between 00:05 and 00:20 (UTC+3). I have not tried the old versions, how I will try, I will write down what and how.

**Comment by mroczis** [comment]
Such feature is no longer available due to missing free and reliable geolocation 3rd party sources.

**Comment by jeffreykog** [comment]
> Such feature is no longer available due to missing free and reliable geolocation 3rd party sources.

Understandable. But when no geolocation name is known NetMonster also doesn't report any GPS location to data servers when submitting a newly detected cell. Would it be possible to always fill this GPS location if the user has granted location permission to NetMonster? Not a core issue, but maybe something that is fixable. Thanks!
